#!/usr/bin/env python3

import subprocess

from nm_script import user_input


def main():
    result = subprocess.run(['git', 'branch'], stdout=subprocess.PIPE)
    as_string = result.stdout.decode('utf-8').strip().splitlines()
    branches = [x.lstrip("*").strip() for x in as_string]
    for branch in branches:
        if user_input.is_yes(f"Delete {branch}?\n"):
            subprocess.run(['git', 'branch', '-D', branch])


main()
