#!/usr/bin/env python3

import argparse
import json
from dataclasses import dataclass


@dataclass
class Arguments():
    suffix: str
    input_file: str
    output_file: str


def main():
    args = parse_args()
    append_suffix(args)


def append_suffix(args: Arguments):

    with open(args.input_file, 'r') as infile:
        words = json.load(infile)

    with_suffix = [
        word if word.endswith(args.suffix) else '{}{}'.format(
            word, args.suffix) for word in words
    ]

    with open(args.output_file, 'w') as output_file:
        json.dump(with_suffix, output_file)


def parse_args() -> Arguments:
    parser = argparse.ArgumentParser(
        description='Map values using a lookup table')
    parser.add_argument('--suffix',
                        type=str,
                        required=True,
                        help='Suffix to append')

    parser.add_argument('--input-file',
                        type=str,
                        required=True,
                        help='list of values to append suffix to')

    parser.add_argument('--output-file',
                        type=str,
                        required=True,
                        help='output destination file')

    args = parser.parse_args()

    return Arguments(args.suffix, args.input_file, args.output_file)


main()
