#!/usr/bin/env python3

import argparse
import json
from collections import Counter
from dataclasses import dataclass


@dataclass
class Arguments():
    input_file: str
    output_file: str


def main():
    args = parse_args()
    count(args)


def count(args: Arguments):
    with open(args.input_file, 'r') as infile:
        values = dict(Counter(json.load(infile)))

    with open(args.output_file, 'w') as outfile:
        json.dump(values, outfile)


def parse_args() -> Arguments:
    parser = argparse.ArgumentParser(
        description='Run counter on a list of values')

    parser.add_argument('--input-file',
                        type=str,
                        required=True,
                        help='Name of input file')

    parser.add_argument('--output-file',
                        type=str,
                        required=True,
                        help='Name of output file')
    args = parser.parse_args()
    return Arguments(args.input_file, args.output_file)


main()
