#!/usr/bin/env python3

import argparse
import json
import pprint
import sys
from collections import Counter
from dataclasses import dataclass

pp = pprint.PrettyPrinter(indent=4)

LIMIT = 50


@dataclass
class Arguments():
    n: int


def main():
    lines = [line.strip() for line in sys.stdin.readlines()]
    arguments = parse_args()
    values = Counter(lines).most_common(arguments.n)
    pp.pprint(values)


def parse_args() -> Arguments:
    parser = argparse.ArgumentParser(
        description='Get n most common from a list of values')
    parser.add_argument('--n',
                        type=int,
                        required=False,
                        default=LIMIT,
                        help='k most common')

    args = parser.parse_args()

    return Arguments(args.n)


main()
