#!/usr/bin/env python3

import argparse
import csv
import json
from dataclasses import dataclass
from typing import List


@dataclass
class Arguments():
    input_file: str
    output_file: str


def main():
    args = parse_args()
    to_csv(args)


def to_csv(args: Arguments):

    with open(args.input_file, 'r') as infile:
        json_values = json.load(infile)

    with open(args.output_file, 'w') as outfile:
        writer = csv.writer(outfile)
        writer.writerow(['key', 'value'])

        for key, value in json_values.items():
            writer.writerow([key, value])


def parse_args() -> Arguments:
    parser = argparse.ArgumentParser(
        description='Convert simple dictionary to csv')

    parser.add_argument('--input-file',
                        type=str,
                        required=True,
                        help='keys and values (json)')

    parser.add_argument('--output-file',
                        type=str,
                        required=True,
                        help='output destination file (csv)')

    args = parser.parse_args()

    return Arguments(args.input_file, args.output_file)


main()
