#!/usr/bin/env python3

import argparse
import json
from dataclasses import dataclass
from typing import Dict

import pandas as pd


@dataclass
class Arguments():
    one: str
    two: str
    output_file: str


def main():
    args = parse_args()
    write_column(args)


def write_column(args: Arguments):

    with open(args.one, 'r') as infile:
        one = json.load(infile)

    with open(args.two, 'r') as infile:
        two = json.load(infile)

    d: Dict[str, str] = {}

    for val1, val2 in zip(one, two):
        d[val1] = val2

    with open(args.output_file, 'w') as outfile:
        json.dump(d, outfile)


def parse_args() -> Arguments:
    parser = argparse.ArgumentParser(
        description='Fetch values from the column of an excel file')
    parser.add_argument('--one',
                        type=str,
                        required=True,
                        help='Path to first file')
    parser.add_argument('--two',
                        type=str,
                        required=True,
                        help='Path to second file')
    parser.add_argument('--output-file',
                        type=str,
                        required=True,
                        help='Name of output file')
    args = parser.parse_args()
    return Arguments(args.one, args.two, args.output_file)


main()
